version: '3.8'

services:
  tracksat:
    build: .
    container_name: tracksat-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: yarn dev --host
